// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSewAxa9IposWbAUpZNWYSuR9ariq7qc',
    appId: '1:666364750426:web:b026978af071cc47558663',
    messagingSenderId: '666364750426',
    projectId: 'business-cpu-bf6e4',
    authDomain: 'business-cpu-bf6e4.firebaseapp.com',
    storageBucket: 'business-cpu-bf6e4.appspot.com',
    measurementId: 'G-SP5956ZMGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaZ1rjyuNBgIRChbLx2UpKGcseCF5Gc7g',
    appId: '1:666364750426:android:0d84ebe5a7d4ab30558663',
    messagingSenderId: '666364750426',
    projectId: 'business-cpu-bf6e4',
    storageBucket: 'business-cpu-bf6e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-pn92tto_t44imFZXimFS4U75H95C-w',
    appId: '1:666364750426:ios:54db9ed125b17692558663',
    messagingSenderId: '666364750426',
    projectId: 'business-cpu-bf6e4',
    storageBucket: 'business-cpu-bf6e4.appspot.com',
    iosClientId: '666364750426-m9lmrvepflshephhgqp9o2dkkh9jguuv.apps.googleusercontent.com',
    iosBundleId: 'com.arrowmuse.businessCpu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-pn92tto_t44imFZXimFS4U75H95C-w',
    appId: '1:666364750426:ios:54db9ed125b17692558663',
    messagingSenderId: '666364750426',
    projectId: 'business-cpu-bf6e4',
    storageBucket: 'business-cpu-bf6e4.appspot.com',
    iosClientId: '666364750426-m9lmrvepflshephhgqp9o2dkkh9jguuv.apps.googleusercontent.com',
    iosBundleId: 'com.arrowmuse.businessCpu',
  );
}
